### ISSUE TITLE
Turbo mode question

### ISSUE THREAD

**Issue by gelsas** [reneklootwijk/node-mideahvac#1]
Hello, 

I am currently using this for my midea ac:

https://github.com/ashevchuk/midea-ac/

With the script mentioned above I am able to control every single part of the AC except the turbo mode.

My question now is do you handle the setting of the turbo mode differently?
If yes what exactly is the difference ?

(I am searching for a long time for a solution where the turbo mode would also work for me)

**Comment by reneklootwijk** [comment]
I had a very quick look and it looks like that code is setting the wrong bit in the command.

**Comment by gelsas** [comment]
So this means with your script it should work ? 

If yes I will try to follow your read me and try out your script

**Comment by reneklootwijk** [comment]
On my units it works
