### ISSUE TITLE
OSK-105 - Is this also supported? Failed to authenticate

### ISSUE THREAD

**Issue by jdrzejb** [reneklootwijk/node-mideahvac#14]
Hey,

I have a Rotenso AC at home that I can control using MSmartHome app. I was trying to use this package to build some automation, but I'm getting `Failed to authenticate` error

The discover process works and I'm getting authentication keys

```

Appliance 1:
- Id: 31885837901911
- Host: 192.168.15.114
- Port: 6444
- MAC Address: 3c:20:93:93:12:60
- Serial No.: 0000C331xxxxxxxxxxxxxxxxxx1002849GLL
- Appliance Type: Air Conditioner
- Firmware Version: 8.33.21
- New Encryption Version: true
- UDP Id: f5c03a8834dxxxxxxxxxxxc4bb9aa17f
- Authentication Key: f5c03a8834dxxxxxxxxxxxc4bb9aa17f
- Authentication Token: 38DFB889F783ED24A4A9xxxxxxxxxxxxxxxxxxxxxxxxxxx316166407A9E38A264AE4xxxxxxxxxxxxxxEA240ACC6DA77

Appliance 2:
- Id: 31885837901913
- Host: 192.168.15.115
- Port: 6444
- MAC Address: 3c:20:93:93:13:94
- Serial No.: 0000C331xxxxxxxxxxxxxxxxxx1002849GLL
- Appliance Type: Air Conditioner
- Firmware Version: 8.33.21
- New Encryption Version: true
- UDP Id: f5c03a8834dxxxxxxxxxxxc4bb9aa17f
- Authentication Key: 4142ACFFD260436084C8149C664xxxxxxxxxxxxxxxxxxxxxxxxF546BB73F9507CE
- Authentication Token: 38DFB889F783ED24A4A9xxxxxxxxxxxxxxxxxxxxxxxxxxx316166407A9E38A264AE4xxxxxxxxxxxxxxEA240ACC6DA77

```

But when trying to connect using this script, it's not working anymore

```


// This example required the following modules to be installed:
// npm install node-mideahvac

const appliances = require('node-mideahvac');
const logger = require('winston')

logger.remove(logger.transports.Console)
logger.add(new logger.transports.Console({
  format: logger.format.combine(
    logger.format.timestamp(),
    logger.format.colorize(),
    logger.format.printf(event => {
      return `${event.timestamp}: ${event.message}`
    })
  ),
  level: 'silly'
}))

// Specify your specific information (this information can be determined using the midea-discover tool)
const ac = appliances.createAppliance({
  communicationMethod: 'sk103',
  host: '192.168.15.114',
  id: '',
  key: '',
  token: ''
});

// Any updated status properties will be printed
ac.on('status-update', data => {
  console.log(`Received updates: ${JSON.stringify(data)}`);
});

ac.initialize()
  .then(response => {
    console.log('Initialized, start polling');

    // The status will be polled each 30s, when properties are changed these will be emitted as a
    // status-update
    setInterval(() => {
      ac.getStatus()
        .catch(error => {
          console.log(`Error: ${error.message}`);
        });
    }, 30000);
  })
  .catch(error => {
    console.log(error);
    console.log(`Error: Failed to initialize (${error})`);
  });
```

```
2022-06-27T22:08:08.697Z: SK103.initialize: Entering
2022-06-27T22:08:08.698Z: AC.getCapabilities: Entering
2022-06-27T22:08:08.699Z: SK103._request: Entering with getCapabilities=xxxx
2022-06-27T22:08:08.699Z: SK103._queueCommand: Entering
2022-06-27T22:08:08.699Z: SK103._processQueue: Entering
2022-06-27T22:08:08.699Z: CALL AUTHNTICXATE
2022-06-27T22:08:08.699Z: SK103._authenticate: Entering
2022-06-27T22:08:08.700Z: SK103._connect: Entering
2022-06-27T22:08:08.706Z: SK103._connect: Connected
2022-06-27T22:08:08.707Z: SK103._encode0x8370: Entering with xxxx and msgType=0
2022-06-27T22:08:08.707Z: SK103._queueCommand: Entering
2022-06-27T22:08:08.707Z: SK103._processQueue: Entering
2022-06-27T22:08:08.707Z: SK103._processQueue: Sending 'authenticate' command
2022-06-27T22:08:08.764Z: SK103._dataHandler: Entering with xxxx
2022-06-27T22:08:08.764Z: SK103._dataHandler: Calling handler for the command 'authenticate' in progress
2022-06-27T22:08:08.764Z: SK103._authenticate: Entering callback
2022-06-27T22:08:08.764Z: SK103._authenticate: Received xxxx
2022-06-27T22:08:08.765Z: SK103._processQueue: Failed to authenticate ERROR
2022-06-27T22:08:08.765Z: SK103._request: Entering callback
2022-06-27T22:08:08.765Z: SK103.initialize: Failed to get capabilities of xxx - Failed to authenticate
2022-06-27T22:08:08.765Z: AC.getStatus: Entering
2022-06-27T22:08:08.765Z: SK103._request: Entering with getStatus=xxx
2022-06-27T22:08:08.765Z: SK103._queueCommand: Entering
2022-06-27T22:08:08.765Z: SK103._processQueue: Entering
2022-06-27T22:08:08.765Z: CALL AUTHNTICXATE
2022-06-27T22:08:08.765Z: SK103._authenticate: Entering
2022-06-27T22:08:08.765Z: SK103._connect: Entering
2022-06-27T22:08:08.771Z: SK103._connect: Connected
2022-06-27T22:08:08.771Z: SK103._encode0x8370: Entering with xxx and msgType=0
2022-06-27T22:08:08.771Z: SK103._queueCommand: Entering
2022-06-27T22:08:08.771Z: SK103._processQueue: Entering
2022-06-27T22:08:08.771Z: SK103._processQueue: Sending 'authenticate' command
2022-06-27T22:08:08.875Z: SK103._dataHandler: Entering with xxxx
2022-06-27T22:08:08.875Z: SK103._dataHandler: Calling handler for the command 'authenticate' in progress
2022-06-27T22:08:08.876Z: SK103._authenticate: Entering callback
2022-06-27T22:08:08.876Z: SK103._authenticate: Received xxxx
2022-06-27T22:08:08.876Z: SK103._processQueue: Failed to authenticate ERROR
2022-06-27T22:08:08.876Z: SK103._request: Entering callback
2022-06-27T22:08:08.876Z: SK103.initialize: Failed to get current status of xxxx - Failed to authenticate
<ref *1> DerivedLogger {
  _readableState: ReadableState {
    objectMode: true,
    highWaterMark: 16,
    buffer: BufferList { head: null, tail: null, length: 0 },
    length: 0,
    pipes: [
      [Console],
      [Console],
      [Console],
      [Console],
      [Console],
      [Console],
      [Console]
    ],
    pipesCount: 7,
    flowing: true,
    ended: false,
    endEmitted: false,
    reading: false,
    sync: false,
    needReadable: true,
    emittedReadable: false,
    readableListening: false,
    resumeScheduled: false,
    paused: false,
    emitClose: true,
    autoDestroy: false,
    destroyed: false,
    defaultEncoding: 'utf8',
    awaitDrain: 0,
    readingMore: true,
    decoder: null,
    encoding: null
  },
  readable: true,
  _events: [Object: null prototype] {
    prefinish: [Function: prefinish],
    end: [
      [Function],
      [Function],
      [Function],
      [Function],
      [Function],
      [Function],
      [Function]
    ],
    data: [
      [Function: ondata],
      [Function: ondata],
      [Function: ondata],
      [Function: ondata],
      [Function: ondata],
      [Function: ondata],
      [Function: ondata]
    ]
  },
  _eventsCount: 3,
  _maxListeners: undefined,
  _writableState: WritableState {
    objectMode: true,
    highWaterMark: 16,
    finalCalled: false,
    needDrain: false,
    ending: false,
    ended: false,
    finished: false,
    destroyed: false,
    decodeStrings: true,
    defaultEncoding: 'utf8',
    length: 0,
    writing: false,
    corked: 0,
    sync: false,
    bufferProcessing: false,
    onwrite: [Function (anonymous)],
    writecb: null,
    writelen: 0,
    bufferedRequest: null,
    lastBufferedRequest: null,
    pendingcb: 0,
    prefinished: false,
    errorEmitted: false,
    emitClose: true,
    autoDestroy: false,
    bufferedRequestCount: 0,
    corkedRequestsFree: CorkedRequest {
      next: null,
      entry: null,
      finish: [Function (anonymous)]
    }
  },
  writable: true,
  allowHalfOpen: true,
  _transformState: {
    afterTransform: [Function: bound afterTransform],
    needTransform: true,
    transforming: false,
    writecb: null,
    writechunk: null,
    writeencoding: 'utf8'
  },
  silent: undefined,
  format: Format { options: {} },
  defaultMeta: null,
  levels: {
    error: 0,
    warn: 1,
    info: 2,
    http: 3,
    verbose: 4,
    debug: 5,
    silly: 6
  },
  level: 'info',
  exceptions: ExceptionHandler { logger: [Circular *1], handlers: Map(0) {} },
  rejections: RejectionHandler { logger: [Circular *1], handlers: Map(0) {} },
  profilers: {},
  exitOnError: true,
  [Symbol(kCapture)]: false
}
Error: Failed to initialize ([object Object])
2022-06-27T22:08:09.266Z: SK103._processQueue: Entering
2022-06-27T22:08:09.267Z: DISCONNECT BECAUSE MPTY QUEUE
2022-06-27T22:08:09.268Z: SK103._processQueue: No queued commands
2022-06-27T22:08:09.269Z: SK103._connect: Connection closed
2022-06-27T22:08:09.377Z: SK103._processQueue: Entering
2022-06-27T22:08:09.377Z: DISCONNECT BECAUSE MPTY QUEUE
2022-06-27T22:08:09.377Z: SK103._processQueue: No queued commands
2022-06-27T22:08:38.785Z: SK103._connect: Disconnect received from appliance
2022-06-27T22:08:38.788Z: SK103._connect: Connection closed
```

Am I assuming right that API for OSK-105 is different than for the OSK-103 and it won't work unless I replace the module?

**Comment by reneklootwijk** [comment]
You must fill in the id, token and key that you determined using the discover command in the script.

**Comment by jdrzejb** [comment]
Hey, @reneklootwijk

Sorry if I was not clear with that. I used the values provided by discover script, but only redacted the values when creating this issue. 

I have ordered a new usb stick to check if the problem is caused by the OSK-105, as it seems that there is only me having this problem.

**Comment by eddee54455** [comment]
Hey, @reneklootwijk <https://github.com/reneklootwijk>

Just to confirm.... It appears that the OSK-105 does indeed seem to be the
source of the error...(My enviro is node-red with the latest Midea node
that is published... The previous version of the Midea node-red node gave
me functionality, but was a PITA and unsatisfactorily unreliable due to bad
internet connectivity in my area...)

I have 3x Aircons, (Alliance Split Units), all using the OSK-105 ... All of
them have the same symptoms as mentioned before...

Ed

**Comment by reneklootwijk** [comment]
If someone can me provide with a sk105 I can have a look.

**Comment by jdrzejb** [comment]
@reneklootwijk I can send one of mine SK105 to you. How can I reach out to you?

**Comment by lovro995** [comment]
Hello guys. I also have the same "Failed to authenticate" problem with my Midea extreme save pro ac, sk105, while discover process works as expected. @jdrzejb have you got any progress with solving your issue? @reneklootwijk I'll be happy to help you guys test the changes if necessary..

**Comment by davidacampos** [comment]
Hi all, just wanted to add that I also have the same issue, also with an SK105 (which I tried getting an SK103, but it seems they are getting harder to get). That been said, what I really wanted to add was that the following project seems to be somehow supporting the SK105 (in what it seems also local mode), so maybe they already figured out the new protocol?

https://github.com/nbogojevic/midea-beautiful-air

**Comment by reneklootwijk** [comment]
Midea Air is deprecated, and some time ago it was no longer possible to obtain the token and key using the Midea Air credentials, so I changed to supporting the msSmartHome credentials and decommissioned support for using Midea Air credentials. The protocol also changed slightly when the token and key obtained using the msSmartHome credentials, so using a token and key obtained using the Midea Air credentials will not work.

**Comment by davidacampos** [comment]
Hey @reneklootwijk , I'm not saying I'm right, just wanted to share the exact steps that I followed... 

1. Downloaded and installed https://play.google.com/store/apps/details?id=com.midea.aircondition.obm
2. Created a new account on that app (i.e. Midea Air).
3. Ran ```pip install --upgrade midea-beautiful-air```
4. Ran ```midea-beautiful-air-cli discover --account ACCOUNT_EMAIL --password PASSWORD --credentials``` using the same credentials as defined in step 2
5. Ran ```midea-beautiful-air-cli status --ip APPLIANCE_IP_ADDRESS --token TOKEN --key KEY``` using the values from step 4

That does spit out the right values, and I can actually run the "set" command to make changes to the unit. I tried this with 2 different SK105 dongles.

I don't have a network sniffer in place to see if it is really calling it locally or not... but I can test blocking the internet access to the dongle to see if it's still working after the fact.

Could it be that something changed again recently?

**Comment by reneklootwijk** [comment]
Yes, that is what I tried to explain. You are using Midea Air credentials to obtain a token and key. Midea Air is using old versions of the endpoints requiring a slightly different protocol. Midea urges you to migrate to msmarthome which requires your account to be migrated. msmarthome uses new endpoints and a slightly different protocol. This module only supports msmarthome credentials and therefor only tokens and keys obtained using these credentials.

**Comment by dkomljenovic2502** [comment]
Hi,
Was this fixed in a way? or is the resolution will not fix? 

Thanks!

**Comment by reneklootwijk** [comment]
I posted version 0.3.0 in January this year where I fixed the signing of packets during discovery (Midea has again changed this).  Although there where other issues reported related to this one, no one tested or reported the outcome. So I closed the issue. For me it is working, but then again I have OSK103 instead of OSK105. So it would be great of you can try version 0.3.0 and report back whether or not it worked for you.

**Comment by VOPAtec** [comment]
Hello reneklootwijk,
thanks for the work you have done so far.
I have installed:
![grafik](https://github.com/reneklootwijk/node-mideahvac/assets/109474110/465589ad-55b0-4257-8f79-ea255a9e3480)

After a few problems with the username I get ID, Key and Token.
But after it was short green connected, I'm getting also "Failed to authenticate" and red error.
I have a SK105 adapter and a Comfee EcoCoolPro2.9 AC.
I dont know were to get these logs from, so I can't give some more hints.
Do i have the right version?

**Comment by reneklootwijk** [comment]
I do not know which version you are using. The node-red module has not been created by me so I do not know anything about it. I do not know which version of module is being used and how it is used. So you better ask the question to the creator of that module.

**Comment by VOPAtec** [comment]
Thank you for your replay. 
Sorry for the confusion. 
I looked at the page of the creator and his last uploade is 9 months ago and your "0.3.0" 6 months. So I think it is not possible that he used it.
If you are intrested how your code is used: https://github.com/twocolors/node-red-contrib-midea-hvac
My programming skill is far away from creating owen code, so I have to ask and hope.
Thanks for your time and have a nice day.
