### ISSUE TITLE
Problem with Rotenso AC

### ISSUE THREAD

**Issue by wojciewa** [reneklootwijk/node-mideahvac#15]
I have a Rotenso AC at home that I can control using MSmartHome app. I was trying to discover Key/Token pair but I got following results:

Appliance 1:
- Id: 146235046505367
- Host: 192.168.0.235
- Port: 6444
- MAC Address: d4:84:57:4a:62:90
- Serial No.: 000000P0000000Q1D484574A62900000
- Appliance Type: Air Conditioner
- Firmware Version: 9.33.34
- New Encryption Version: true
- UDP Id: 42aaadaf7bxxxxxx2b832b2fdb2f3952
- Authentication Key: **An unknown error occurred**
- Authentication Token: **An unknown error occurred**

Any ideas whats then?

**Comment by reneklootwijk** [comment]
I will add a debug option to thee next version of discovery to provide some debug logging, but for now can you edit the discovery script which is in de node_modules/.bin directory and change:
`level: 'nonegit'`
to
`level: 'debug'`

**Comment by reneklootwijk** [comment]
I released an updated version of the code. Can you give it a try?

**Comment by reneklootwijk** [comment]
Closed because no response
