### ISSUE TITLE
Status feedback SerialBridge

### ISSUE THREAD

**Issue by Fillip38** [reneklootwijk/node-mideahvac#17]
Hello,
I switched over in the meantime and use the whole thing with the serial bridge. I control the whole thing via NodeRed, but I have problems or I don't get any "feedback". I can switch on and control the air conditioning, but there is no status back via the module... Do I have to set or "request" something?

**Comment by Fillip38** [comment]
If i send a payload "getStatus" i becam a "Invalid response", sometimes "No response received"

**Comment by reneklootwijk** [comment]
Feedback is provided in two different ways; via status-update events and via a response (promise) on every command.

Looks like there is a fault in the rx connection of your adapter. Can you enable [logging](https://github.com/reneklootwijk/node-mideahvac#logging) and provide these here?

**Comment by Fillip38** [comment]
Ich nutze das ganze aktuell im Versuchsaufbau mit einem ESP01 und einer passenden Adapterplatine, habe mir bereits bei JLCPCB den "Universal IoT dongle" geordert.
Komischerweise bekomme ich einmal am Tag rib Statusupdate der Klimaanlage rein, aber wenn ich dieses manuell anstoße bekomme ich wie gesagt immer den Fehler. Muss denn die Klimaanlage laufen um den Status zu übermitteln? 
Vermutlich nicht, denn heute kamen bsp. Um 12:40 die Daten rein, da war die Klimaanlage nicht aktiv...

**Comment by reneklootwijk** [comment]
The airco does not have to be turned on to receive a status update, but the airo never send a status update by itself only per request. Did  you try the example code for the sk103 option (in the example directory)? I do not know anything on node-red.
