### ISSUE TITLE
Should it works with Qlima SC5248 ?

### ISSUE THREAD

**Issue by AirBeeSee** [reneklootwijk/node-mideahvac#5]
May be , it s me  or it s not compatible.
I'm not an expert with ESP module but I think I ve done the correct setup. 

I bought : https://www.amazon.fr/gp/product/B07Y8JZNCQ/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1
i've flash with esp-link V2.2.3  ( and 3.0.14 to test)
I can connect to the esp-link web page and configure wifi and other params (perhaps it s something there)

but , after that , I think i 'skip' something. 
if I run the serialbridge sample (and yes I put my ip and port ;) ) and go step by step in visual studio code 
the connect step is ok , but the following operation catch error "No response receive".

<img width="823" alt="Capture d’écran 2020-09-16 à 21 51 37" src="https://user-images.githubusercontent.com/57507903/93385653-d4470c00-f866-11ea-80f6-c85640ab2411.png">

If I look at the "Microcontroller Console" on the esp web interface, nothing appears.
and in the debug console , I get "286732> Accept port 23, conn=0x3fff7580, pool slot 0"
<img width="931" alt="Capture d’écran 2020-09-16 à 21 50 13" src="https://user-images.githubusercontent.com/57507903/93385563-b7123d80-f866-11ea-9dca-587cbf668c04.png">
<img width="937" alt="Capture d’écran 2020-09-16 à 21 50 27" src="https://user-images.githubusercontent.com/57507903/93385570-b9749780-f866-11ea-8638-dbc671ffe0cd.png">
<img width="875" alt="Capture d’écran 2020-09-16 à 21 50 52" src="https://user-images.githubusercontent.com/57507903/93385581-bc6f8800-f866-11ea-9e2e-7d5072f7e766.png">

**Comment by reneklootwijk** [comment]
Are you sure the TX and RX pins are not switched?

**Comment by AirBeeSee** [comment]
I ve try the option « swap » uart pins in the pin assignment screen.
May be the usb connector is not soldered how it should to work with ac ?
But , I think if it was not correct , the esp should not boot and works when I plug in ac usb slot

**Comment by reneklootwijk** [comment]
I do not understand what you are trying to say.

**Comment by AirBeeSee** [comment]
![E52CF7B0-0E0D-41DD-B587-87474AF2FCCE](https://user-images.githubusercontent.com/57507903/93396649-50961b00-f878-11ea-8327-49646271501a.jpeg)

**Comment by reneklootwijk** [comment]
This will bot work swapping means using complete different pins but the levelshifter adapter is connect to specific pins. What I meant is did you try to switch the rx and tx pins, so where you connected rx now connect tx and vice versa.

**Comment by AirBeeSee** [comment]
I use a usb to esp bought on Amazon 
![706DDF56-05E8-4D86-B2AA-573890E6AC67](https://user-images.githubusercontent.com/57507903/93650077-ce3f5f80-fa0d-11ea-8268-5d10cc2b05af.jpeg)

And , if I monitor usb on my computer, i can send and receive in esp-link console.

I bough this module because I'm not very good at doing electronics

**Comment by reneklootwijk** [comment]
That does not work. Although your AC unit has an usb connector it is not a usb interface, it is just a serial ttl interface.

**Comment by AirBeeSee** [comment]
That's what I deduced from your previous comments, I ordered the model you show on GitHub.
Thx

**Comment by AirBeeSee** [comment]
All works perfectly now. with the correct shifter and usb pin assignment.
Thx again ;)
Now I should look at the code.
