### ISSUE TITLE
add support method getUserList on cloud

### ISSUE THREAD

**Issue by twocolors** [reneklootwijk/node-mideahvac#7]
First of all great job (: 

i want rewrite node-red nodes to use you modul but you don't have method getUserList.

plz add method getUserList to get deviceID

https://github.com/twocolors/node-red-contrib-midea/blob/master/lib/midea.js#L79

**Comment by reneklootwijk** [comment]
I will no longer extent support for the Midea cloud. Rationale is it is unstable, to often it is not available at all, it returns errors or it returns incorrect values. But you can create a pull request or clone the repository as a whole and add the features you require.

**Comment by twocolors** [comment]
thx, will wait support original wifi dongl (lan mode)

**Comment by noahbentusi** [comment]
> I will no longer extent support for the Midea cloud. Rationale is it is unstable, to often it is not available at all, it returns errors or it returns incorrect values. But you can create a pull request or clone the repository as a whole and add the features you require.

Excuse me, could you tell me what the URL for the official website of Midea Cloud? I can't find it.
I registered with the midea app(com.midea.ai.appliances) and attached my device.
but, node-mideahvac always telling me that my account did not exist.

I think maybe the account of midae app so different with midea cloud's.

**Comment by low-budget** [comment]
@noahbentusi: I think that you are correct - your account is somehow connected to the version of the app that you used to register your account. The way that I got it to work is to change the "appKey" and "appId" in node-mideahvac/lib/cloud.js to the same values contained in the Andriod apk that I registered with. You can extract the appKey and appId from the apk by using apktool to decompile the apk and then searching for the keywords in the resulting resource files. I found mine in a file called "strings.xml".

PS. Sorry to the other participants for continuing to high-jack this unrelated (and closed) issue.
